const LOAD_TODOS = 'LOAD_TODOS';
const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
const ERROR = 'ERROR';

export {
  ADD_TODO, REMOVE_TODO, TOGGLE_COMPLETE, LOAD_TODOS, ERROR,
};
