const LOAD_CONTACTS = 'LOAD_CONTACTS';
const ADD_CONTACT = 'ADD_CONTACT';
const REMOVE_CONTACT = 'REMOVE_CONTACT';
const FETCH_REQUEST = 'FETCH_REQUEST';
const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_FAILED = 'REQUEST_FAILED';

export {
  LOAD_CONTACTS, ADD_CONTACT, REMOVE_CONTACT, FETCH_REQUEST, REQUEST_FAILED, REQUEST_SUCCESS,
};
